### ISSUE TITLE
Balsamiq Wireframe

### ISSUE THREAD

**Issue by a4ayad** [msimbo/codeofhonors-jobs-tracker-v1v2#2]
Create a draft balsamiq wireframe
Save the draft wireframe on your computer in the bmpr format
Export draft wireframe into PDF format, and attach it to this issue using the following naming convention:

fileName_Initials_VersionNumber. For example, JT_Wireframe_AA_1.pdf

The team will decide on creating a final version of the balsamiq wireframe.

[https://app.zenhub.com/files/323639676/9c1bd24c-b3b4-45aa-911f-b9c3c6534f31/download](https://app.zenhub.com/files/323639676/9c1bd24c-b3b4-45aa-911f-b9c3c6534f31/download)

**Comment by a4ayad** [comment]
[https://app.zenhub.com/files/323639676/2fb87ca3-6632-44ae-8853-0bab81d21552/download](https://app.zenhub.com/files/323639676/2fb87ca3-6632-44ae-8853-0bab81d21552/download)

**Comment by Lamwatk13** [comment]
The first Progress of the wireframe

https://whimsical.com/the-beginning-Tyfd5WLaeMmn7eNAdUgUXC

**Comment by a4ayad** [comment]
Hi @Lamwatk13, I cannot access the link you provided [https://whimsical.com/the-beginning-Tyfd5WLaeMmn7eNAdUgUXC]
Would you please save and/or export the wireframe into a file on your computer and attach it into this issue?

**Comment by Lamwatk13** [comment]
Most recent user journey![user journey draft1_RW.png](https://images.zenhubusercontent.com/5fee16848d2c76262f0aeb43/151baf2b-4e08-4278-97b3-e8901666d4b5)

**Comment by Lamwatk13** [comment]
Wireframe jobtracker


![Jobtracker layout 1.png]

(https://images.zenhubusercontent.com/5fee16848d2c76262f0aeb43/4cec2f0c-4990-45a1-a123-d4b5f4a43bce)

**Comment by abecojc** [comment]
Wireframe 
[https://app.zenhub.com/files/323639676/c7b4fab9-c1be-4ac3-b7d6-695a89a58c61/download](https://app.zenhub.com/files/323639676/c7b4fab9-c1be-4ac3-b7d6-695a89a58c61/download)

**Comment by Lamwatk13** [comment]
New correct Balsamiq wireframe v1

[https://app.zenhub.com/files/323639676/c36eb427-ffc5-434d-aa68-16650e793954/download](https://app.zenhub.com/files/323639676/c36eb427-ffc5-434d-aa68-16650e793954/download)

**Comment by Coding-Edwar** [comment]
I made 2 wireframe pages.

![jobTrackers-v1v2-wf1.png](https://images.zenhubusercontent.com/5ff3767ccb7d78c980425f44/07c880a9-af47-4223-bc02-04c2686419e2)

![jobTrackers-v1v2-wf2.png](https://images.zenhubusercontent.com/5ff3767ccb7d78c980425f44/ca92f4e6-31bc-40d9-b4e3-33c0f8413334)

**Comment by a4ayad** [comment]
AA and EC to create balsamiq wireframes of all the pages.
