### ISSUE TITLE
User Map / Journey

### ISSUE THREAD

**Issue by a4ayad** [msimbo/codeofhonors-jobs-tracker-v1v2#3]
- Create the draft User Map or User Journey using Balsamiq or Whimsical. This is required for the demo.
- Whimsical allows you to export the file into a .PNG format.
- Attach your draft into this issue.
- The team must decide on the final version of the User Map or User Journey.

![Journey_AA_1.png](https://images.zenhubusercontent.com/5feca9f102ab50011be818e5/d7ae593d-d5b1-4b83-afe9-a186d40c8b0c)

**Comment by jtillman83** [comment]
![user journey JT-1.png](https://images.zenhubusercontent.com/5fecf0bf0e63be23a966700f/3699d0c0-faac-4572-97c7-45cca13d0cb4)

Created a workflow chart wanted to document all the processing steps to be clear in what i wanted the user to go thru.

**Comment by Lamwatk13** [comment]
log on journey 

https://balsamiq.cloud/sa8ti6e/pl9x2wh

**Comment by a4ayad** [comment]
*Thank you* @jtillman83, I was able to view your first draft of the user map / journey. I saved/exported into UserJourney_JT_1.png and attached it to this issue:


![UserJourney_JT_1.png](https://images.zenhubusercontent.com/5feca9f102ab50011be818e5/96595ae3-6f96-4a47-bdc4-5776b07934d2)

**Comment by abecojc** [comment]
user map

![usermap-draft2.png](https://images.zenhubusercontent.com/5fee08f70e63be090866720c/bfcad134-5667-4945-8808-e5b388876c5c)

**Comment by abecojc** [comment]
https://whimsical.com/join/na8QsC7WL1hsJCFNHRU5p?invite=jmg65chs

**Comment by Coding-Edwar** [comment]
This my journey map

![EC-sprint5-map.png](https://images.zenhubusercontent.com/5ff3767ccb7d78c980425f44/f58afa77-3c47-4717-bff0-dda8dd0854ff)

**Comment by a4ayad** [comment]
I added Dele to the assignee list.

**Comment by a4ayad** [comment]
Everyone, please update this issue page with a link to your whimsical page if it is not there already.

**Comment by Coding-Edwar** [comment]
https://whimsical.com/join/FN6yjmJFXeasfT4KKiqVP3?invite=ac2d6b3r

**Comment by a4ayad** [comment]
Sections

feat/home
-home page - AA

feat/sign-register
- sign in page / form - EC
- register account page  -EC

feat/search
- search page / form - AR
   - 2 criteria fields
   - Search button

feat/results
- job's list - JT
  - 3 criteria fields

feat/job-details
- job detail - RW
  - share job listing details
  - Favorites

![CodeOfHonor (1)](https://user-images.githubusercontent.com/73318960/104057273-ddfed180-51bf-11eb-910b-2dd23451e567.png)

**Comment by deletosh** [comment]
@a4ayad what are you asking of me here? Please clarify?

**Comment by a4ayad** [comment]
Hi @imdeletosh , I added you to this issue in case you want to give us feedback on the final version of the User Map / Journey.

**Comment by a4ayad** [comment]
Hi @imdeletosh,

When you get a chance, please  go to our whimsical board 

https://whimsical.com/codeofhonor-7aAar1JJwqeGmrg1xR5u9h

and give us feedback.

Thanks

**Comment by deletosh** [comment]
@a4ayad  this simplified version rings better.

I will like the team to break out all the features/tasks that will be needed to do this on the Whimsical board (don't worry about assign yet)

cc 
@abecojc  @edeced  @jtillman83 @Lamwatk13 @imaalim

**Comment by a4ayad** [comment]
Romaine wrote:

The first Progress of the wireframe

https://whimsical.com/the-beginning-Tyfd5WLaeMmn7eNAdUgUXC
