### ISSUE TITLE
Brainstorm and create tasks

### ISSUE THREAD

**Issue by a4ayad** [msimbo/codeofhonors-jobs-tracker-v1v2#5]
Brainstorm and discuss on how to break the project into smaller tasks

**Comment by jtillman83** [comment]
we must come together and chose the wireframe and workflow soon

**Comment by a4ayad** [comment]
Video
Take notes
Apply

Jan 1st: Fri JT 3-4pm, RW 3-4pm, AR apologies,
share your user journey and balsamiq wireframe

**Comment by a4ayad** [comment]
Link to Nimbus page
http://nimb.ws/R2iIlB

**Comment by Lamwatk13** [comment]
ok please something

**Comment by a4ayad** [comment]
Friday 1/8

List of tasks

Whimsical user map Done

BoilerPlate: setup before start coding, dependencies, yarn install, npm, leg work 1/11
- See issue #18 created by EC
- Repeat for each github branch

Create github branches as described on the user 

- feat/home
- feat/sign-register
- feat/search
- feat/results
- feat/job-details

Each member must create their html, css, js for their tasks


User account
Input: email, password

Registration form - EC
Login and signup form - EC

Access entry of API - All

JSON API reorganize by categories [css,html]

Arrays to store data

Pull raw data at monster.com

Select what to display

https://partner.monster.com/job-search

Research and document how to access API data from job search engines

Notes from 1/5/2021 meeting
For sign-in and sign-up forms
Form creation
form validation
Account
How to get the API data from Monster.com

Find, share and Read the instructions

for example: https://partner.monster.com/job-search

Access key 

index.html 1 2 3 4
app.js
package.json
css files

practice git commands from the folder in our computer into the msimbo repo

**Comment by a4ayad** [comment]
1-3.20pm

AA and EC to create balsamiq wireframes of all the pages.

Create Logo "Job Tracker"
JT see suggestions and posted link

EC
Implement the wireframe into the html page.
boiler plate

AA:
implement the wireframe into the html page.
boiler plate

AR:
implement the wireframe into the html page.
boiler plate
Think of ways to implement the suggestions/auto-complete feature

limit list of locations to 5 cities

if no match, Sorry, we didn't find any jobs matching your criteria


JT: implement the wireframe into the html page.
boiler plate
logo

RW: implement the wireframe into the html page.
boiler plate

All: make list of task related to JS, categories, API
look at example of arrays
