### ISSUE TITLE
ZENHUB link not working for two members

### ISSUE THREAD

**Issue by a4ayad** [msimbo/codeofhonors-jobs-tracker-v1v2#8]
Good morning Dele Omotosho, 

When I shared the zenhub link 

https://app.zenhub.com/workspaces/msimbo-5feb4fd93aedd00012fb4ba4/board?repos=323639676 

with Jiannina Tillman and Romaine Watkins, somehow their chrome browser changes the last digits of the url 323639676  into another number, and they see a different zenhub page. We tried different approaches to debug the issue with no success. Would you be able to join us for a 5min session to help us debug the issue? 

Best,
Ahmed

**Comment by deletosh** [comment]
@a4ayad coming on.

**Comment by jtillman83** [comment]
when I come here I don't see any issues

**Comment by jtillman83** [comment]
it works now thanks
